### ISSUE TITLE
openxr project cannot open in unreal4.27

### ISSUE THREAD

**Issue by tahoorasf1** [microsoft/Microsoft-OpenXR-Unreal#33]
I also cannot open the project in unreal 4.27. it said that Microsoft openxr is for 26, although I install it from epic on both versions26 and 27.  even if I accept this and run it on 4.27version. with that version, I cannot run the project and I get lots of errors. here is a sample of the image you can see
<img width="1793" alt="2021-11-17 18_43_46-MsftOpenXRGame - Unreal Editor" src="https://user-images.githubusercontent.com/75256061/142254669-5321a6d0-be71-43f6-b9b1-4646539e4890.png">

**Comment by fieldsJacksonG** [comment]
Change this line from "4.**26**.0" to "4.**27**.0" :
https://github.com/microsoft/Microsoft-OpenXR-Unreal/blob/fccb12a31070bab0d45e8e948f809e6dbdde5937/MsftOpenXRGame/Plugins/MicrosoftOpenXR/MicrosoftOpenXR.uplugin#L13

Then right click on the uproject and select "Generate Visual Studio project files"

This happens because the source project and plugin are developed in 4.26 so we can maintain backwards compatibility.

The releases here: https://github.com/microsoft/Microsoft-OpenXR-Unreal/releases
have already done this (see 4.27.zip in each release's "Assets" dropdown), which are then uploaded to the Unreal Marketplace.

**Comment by tahoorasf1** [comment]
@fieldsJacksonG 
thanks for answering I check your answer. it is not from there. the EngineVersion in MicrosoftOpenXR.uplugin was 4.27.0. I still get the same errors. and the release version 4.27.zip is not working. so I cannot even open it on my computer.

![2021-11-19 15_36_28-MsftOpenXRGame - Unreal Editor](https://user-images.githubusercontent.com/75256061/142640792-88906bb6-2561-4665-9f4f-20753e74d3d7.png)
.

**Comment by fieldsJacksonG** [comment]
How are you opening the project after changing the version to 4.27 (from 4.26)?
Are you right-clicking on the uproject and switching the engine version to 4.27, then opening the sln and building from Visual Studio?

I can repro this by opening the 4.26 project (from GitHub source) from a 4.27 engine and converting as a copy.  This looks like what you have done, since the " 427" appended to your project name "MsftOpenXRGame 4.27" is added from a 4.27 copy-conversion.  However, after I change the uplugin file to 4.27, this does go away for me.

Please make sure you have modified the uplugin file in "C:\users\stud8\Desktop\projectopenxr\Microsoft-OpenXR-Unreal\**MsftOpenXRGame 4.27**\Plugins\MicrosoftOpenXR" rather than the original source  "C:\users\stud8\Desktop\projectopenxr\Microsoft-OpenXR-Unreal\**MsftOpenXRGame**\Plugins\MicrosoftOpenXR"

**Comment by tahoorasf1** [comment]
I fixed it myself. after changing the version of the project the way you told me. I deleted the plugin 4.27 and put the latest version from the GitHub inside of the project. then It will work correctly.
