### ISSUE TITLE
Failed to find VCLibs.arm64.14.00

### ISSUE THREAD

**Issue by NXTler** [microsoft/Microsoft-OpenXR-Unreal#72]
Hey,
I'm currently trying out the HoloLens 2 and started to build up a small test in Unreal Engine.
I got some errors while packaging I quickly fixed, though I'm stuck on this one.
Thanks for your guys help.

UATHelper: Packaging (HoloLens): Failed to copy C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\Appx\Retail\arm64\Microsoft.VCLibs.arm64.14.00.appx to C:\Sework\HoloLens\Saved\StagedBuilds\HoloLens\Microsoft.VCLibs.arm64.14.00.appx, deleting, waiting 10s and retrying.
UATHelper: Packaging (HoloLens): Skip copying file C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\Appx\Retail\arm64\Microsoft.VCLibs.arm64.14.00.appx because it doesn't exist.

**Comment by lucoiso** [comment]
Same problem with the [5.0.0_Marketplace.zip](https://github.com/microsoft/Microsoft-OpenXR-Unreal/releases/download/1.1.14/5.0.0_Marketplace.zip) version from https://github.com/microsoft/Microsoft-OpenXR-Unreal/releases/tag/1.1.14 ;

**SO:** Windows 11 Home 21H2 22000.778;
**Windows SDK:** Tried both 10.0.22621.1 (got WinRT errors w/ this version) and 10.0.18362.1 versions;
**UE:** 5.0.2

Some info: Don't have the emulator installed because my SO version doesn't support Hyper-V, instead i've installed the Mixed Reality Portal and OpenXR Tools for windows.

Tried reinstalling the C++ redistributable and repairing the Windows SDK and i'm still getting the same errors (Microsoft.VCLibs.arm64.14.00.appx doesn't exist)

**Comment by lucoiso** [comment]
I found a solution:
The problem is that I didn't install the build tools for UWP apps

1. Open Visual Studio Installer.
2. Click Modify according to your Visual Studio version (I'm using Visual Studio 2022 preview 2.0)
3. Go to the Individual Components tab
4. Search for: C++ Universal Windows Platform support for vXXX build tools (ARM64) - replace vXXX with your build tools version (v143 if you're using Visual Studio 2022, v142 if VS2019, etc)
5. Check the build tools and click Modify.

![image](https://user-images.githubusercontent.com/77353979/176945392-0b7c5d90-246c-4fd8-9d85-1b5f34e19920.png)
