### ISSUE TITLE
Can't get Tracking State [UE5]

### ISSUE THREAD

**Issue by Tim-Potratz** [microsoft/Microsoft-OpenXR-Unreal#88]
Hello,
as you can see from [this issue](https://github.com/microsoft/MixedReality-UXTools-Unreal/issues/65) I have made the switch to OpenXR. After some testing around, I notice that the tracking state of my QR-Code is allways set to "Tracking" even if it's not visible.

Unreal Engine 5.0.3
Visual Studio 2022, 17.3.1
Hololens 2, 20348.1522
OpenXR 1.1.14

**Comment by fieldsJacksonG** [comment]
This seems to be by design: the QRCode is tracked from a node in the spatial graph.  When a QRCode is identified, a node is created and located with xrLocateSpace.  Even if the QRCode is taken off the wall or not in view, xrLocateSpace can still find the location of a node in the graph provided the tracking system has enough data.

However, the UpdateTrackedGeometry event will not fire unless the QR code is currently being seen by the HoloLens.  So if you look away or remove the QR code from the wall, the tracking system won't try to locate the QRCode and it will persist at its last-known location.

The recommendation from the team that wrote the QR package is to ignore QRCodes that have not updated for some time:
https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/qr-code-tracking-overview#managing-qr-code-data
You can do this by checking GetLastUpdateTimestamp on a cached TrackedGeometry, or if you're doing this in blueprint, it may be easier to cache your own GetGameTimeInSeconds on each update, since the tracked geometry is using FPlatformTime::Seconds() which isn't exposed to BP.

**Comment by Tim-Potratz** [comment]
Okay got it, thanks a lot!
I solved this issue by simply ataching a retriggerable Delay, with Set UI Visibilty to Update Tracked Geometry:
![QR-Code fix](https://user-images.githubusercontent.com/112068772/201051547-a5fd1303-7735-4cf3-b3c2-7ca25ae5c5de.PNG)

I would suggest removing the function "Get Tracking State" or add a small note telling that it isn't used anymore, to prevent future issues.
